security:
  oauth2:
    resource:
      filter-order: 3
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/test
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  user:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
jwt:
  CLIEN_ID: shahid_hussain
  CLIENT_SECRET: l@s)-(@R!123
  GRANT_TYPE_PASSWORD: password
  AUTHORIZATION_CODE: authorization_code
  REFRESH_TOKEN: refresh_token
  IMPLICIT: implicit
  SCOPE_READ: read
  SCOPE_WRITE: write
  TRUST: trust
  ACCESS_TOKEN_VALIDITY_SECONDS: 3600
  FREFRESH_TOKEN_VALIDITY_SECONDS: 21600